"""Modifications were made

Revision ID: 23947bdfd19f
Revises: 5c68a9c8ce43
Create Date: 2024-12-10 02:03:01.043330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23947bdfd19f'
down_revision = '5c68a9c8ce43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
