"""Modifications were made

Revision ID: 5c68a9c8ce43
Revises: 6d22d4b37b83
Create Date: 2024-12-10 01:32:36.698235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c68a9c8ce43'
down_revision = '6d22d4b37b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('certificates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificates', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
